Center window on current window
PunchablePlushie/godot-game-settings pull request #27
Opened 2023-05-10 15:59 UTC by Norodix

Changing the window size moves the window to the left monitor on multi-monitor setups.
This change keeps the window on the current monitor after centering.

2023-05-11 05:21 UTC, Norodix commented
I noticed there is even a relevant issue after fixing it for myself.

https://github.com/PunchablePlushie/godot-game-settings/issues/24

2023-05-12 09:42 UTC, PunchablePlushie requested changes
Apologies for the late review. Please make sure everything is statically typed. So:
```
var screen: int = ...
var origin: Vector2i = ...
```
Other than that, everything's fine. Thanks for the fix!

2023-05-12 19:31 UTC, Norodix commented
Added type hints.
Also, turns out I introduced a small bug, but that is fixed now. At one place I used the window_get function with the screen id which is obviously incorrect.

2023-05-13 00:14 UTC, PunchablePlushie approved these changes

2023-05-13 00:15 UTC, merged